### PR TITLE
remove tmp file at exit

### PR DESCRIPTION
**Pull request by wilkpio**
fixes: https://github.com/sclorg/scl-utils/issues/45

### CODE REVIEW

**Comment by voxik** [comment]
I am afraid that the solution is not as easy as it seem, because of:

https://github.com/sclorg/scl-utils/blob/9147d3b66e0a263c2eb427b7892b34c925363854/src/fallback.c#L224-L229

Maybe the temporary script could be extended to delete itself as a last step?

**Comment by wilkpio** [comment]
Corresponding bugzilla created: https://bugzilla.redhat.com/show_bug.cgi?id=2091000

**Comment by ffesti** [comment]
The issue is that both `execl` and `exec` in [line 217](https://github.com/sclorg/scl-utils/blob/9147d3b66e0a263c2eb427b7892b34c925363854/src/fallback.c#L217) replace the current program. So they do not return to the following lines. So not even the script deleting itself as a last step does work as the last line won't be executed.

The script deleting itself in the fist line may work as it should already be opened by the bash (obviously).
Note that the suggested patch should work fine for the non exec code path.

**Comment by ffesti** [comment]
Well, the patch would at least solve some use cases. May be just merge and fix the exec cases separately

**Pull request merged**
