### PR TITLE
Add hook to allow collections to be loaded automatically

### PR DESCRIPTION
**Pull request by jcpunk**
This adds a hook allowing users to automatically enable collections for their current shell.  Some of my users have asked after this feature.

### CODE REVIEW

**Comment by praiskup** [comment]
Hm, this would require touching dotfile - I'd rather prefer to do such things in ~/.profile or ~/.bashrc, ~/.cshrc, etc.

**Comment by jcpunk** [comment]
I understand, my concern is really that I've got a handful of users who don't totally understand the workflow.

With it being in a separate file, I can just quietly pre-populate it for them.

**Comment by praiskup** [comment]
Isn'ŧ it easier to install some system-wide `/etc/profile.d` file, which will actually source your `.sclload` files?

**Comment by jcpunk** [comment]
Right now I've got this PR deployed on my devel hosts.  I just figured I'd share and see if it was worth it upstream.

**Pull request closed without merging**
