### PR TITLE
Adapt env parser to newer module(1) versions. BZ 1618803

### PR DESCRIPTION
**Pull request by dmnks**
With module(1) version 4.x and later (tcl-based), the command

  MODULE_CMD sh load <collection>

prints a newline after each export line, breaking our parsing logic in
get_env_vars() which just tokenizes the output by semicolons and does
not anticipate newlines.  As a result, we would end up with
"\nKEY=VALUE" pairs and pass them as such to putenv(3) which then has no
effect.

The fix is easy; just strip the leading newline from the KEY=VALUE pairs
if present.  This ensures we stay compatible with the older module(1)
versions as well.

A simple reproducer follows:

  1) Make scl(1) run in "modulefile" mode by creating a modulefile in
     /etc/scl/modulefiles corresponding to a collection, for example:

     $ /usr/share/Modules/bin/createmodule.sh /opt/rh/eap7/enable \
       > /etc/scl/modulefiles/eap7

  2) Run a simple scl(1) command to detect the presence of an env var
     that we know should be set in the target collection, for example:

     $ scl enable eap7 'echo $LOADEDMODULES'

     Previously, there would be no output.  With this commit, the output
     should be "eap7".

### CODE REVIEW

**Comment by voxik** [comment]
Any chance to add some test case? :innocent:

**Comment by dmnks** [comment]
Oh OK, that didn't even cross my mind, thanks. Sure :)

**Comment by dmnks** [comment]
@voxik How do I run the test suite? There appears to be one in the `tests/` directory but it's not built by cmake since the relevant directive is commented out. After uncommenting it, cmake fails with `FILE INSTALL cannot find "/home/mdomonko/code/scl-utils/tests/SRPMS".`

**Comment by voxik** [comment]
Oh, WOW, yes, that might be problem. Now I remember that I don't remember to ever know how to run the test suite.

But good start could be to comment out https://github.com/sclorg/scl-utils/blob/master/tests/CMakeLists.txt#L20 and see what actually fails.

Looking into it deeper, it seem that the SRPMs are required by `tests/test_build.sh`, so probably removing last two lines from the `tests/CMakeLists.txt` might get running the other test cases.

**Comment by dmnks** [comment]
Cool, thanks. I'll take a look tomorrow.

**Comment by dmnks** [comment]
@voxik Updated, please re-review.

**Comment by voxik** [comment]
I have enabled Travis-CI for this repo. Do you think you could add reasonable .travis.yml to run the test suite?

Otherwise the changes looks reasonable to me.

**Comment by dmnks** [comment]
Returning to this after 1.5 year... I haven't had a chance to get that .travis.yml file up and running unfortunately, so I'll just merge this now so we can proceed with the next release. We can always add that later.

**Pull request merged**
